updated german translation for 2.2.
goharbor/harbor pull request #13801
Opened 2020-12-17 17:23 UTC by sluetze

Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>

may be WIP, if more wordings in 2.2 are changed.

2020-12-27 21:40 UTC, Vad1mo requested changes
The translation is a bit stiff. There are a few English words still in use although good german word exist also in the IT lingua. 

Roboter-Account -> Roboterkonto
Secret -> Geheimnis

2020-12-27 21:40 UTC, Vad1mo commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "EDIT_ROBOT_SUMMARY": "Bearbeite einen systemweiten Robot-Account. Wähle \"Alle Projekte abdecken\", um den Robot-Accoutn für alle existierenden und zukünftigen Projekte zuzulassen",
Bearbeite ein System Robot Account. Wähle \"Alle Projekte abdecken\", um auf alle bestehenden und zukünftigen Projekte angewendet zu werden.

2020-12-28 08:27 UTC, sluetze commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "UPDATE_ROBOT_SUCCESSFULLY": "Robot aktualisieren erfolgreich",
yes, that's cleaner. I chose the "<Subject> <Verb> erfolgreich" and "<Subject> <Verb> fehlgeschlagen" on purpose. The idea was, that you only have to take a look on the last word to see if something has a positive or negative outcome.
To be consistent with "<Subject> <Verb>" I have to do a "NOT" in the negative outcome. that's something that is often overlooked. Thus users may not see the error.

So i chose a 'bad' translation for a better understandability.

What's your view on this ?

2020-12-28 08:36 UTC, sluetze commented
> The translation is a bit stiff. There are a few English words still in use although good german word exist also in the IT lingua.
> 
> Roboter-Account -> Roboterkonto
> Secret -> Geheimnis

Hi Vadim,
thanks for the review. I will take a look on the specific suggestions later this day.

"Roboterkonto" is unknown to me in the IT. I only know that word from investments.
Secret/Geheimnis is valid. In my environment no IT person talks about "Geheimnis" we often use secret instead or other english terms. that's a common problem in german "IT-Language".

I'm open to translate all Secrets to Geheimnis though if you think that the meaning would be clear to all.

2021-01-08 02:09 UTC, bitsf commented
@sluetze hi, is this PR good enough to merge? 2.2.0 is going to GC.

2021-01-08 08:15 UTC, sluetze commented
> @sluetze hi, is this PR good enough to merge? 2.2.0 is going to GC.

@bitsf, yes good enough to merge. I'll try to contact vadim on slack to work on the stiffness in upcoming PRs.

2021-01-11 05:52 UTC, AllForNothing commented
@sluetze This line has been updated, I may need to translate it:
![image](https://user-images.githubusercontent.com/30999793/104150185-0bdc5400-5414-11eb-9652-ec9d94fd8997.png)
 Ping me if your PR is ready to merge

2021-01-11 16:14 UTC, sluetze commented
@AllForNothing
in 24 hours i'll have a discussion with vadim and maybe we can improve the translation on some parts. If you need to cut out the rc asap, feel free to merge. If you give me 48 hours, I may be able to get the improvements into this PR.

just don't want to block the RC, since the translation is usable.

2021-01-12 05:56 UTC, AllForNothing commented
> @AllForNothing
> in 24 hours i'll have a discussion with vadim and maybe we can improve the translation on some parts. If you need to cut out the rc asap, feel free to merge. If you give me 48 hours, I may be able to get the improvements into this PR.
> 
> just don't want to block the RC, since the translation is usable.

@sluetze I'll merge this PR this Friday, then you will have enough time to improve your translation

2021-01-12 16:45 UTC, sluetze commented
@Vad1mo , ready for review / comments

2021-01-18 02:30 UTC, AllForNothing commented
@sluetze Please rebase your code.

2021-01-18 16:12 UTC, sluetze commented
@AllForNothing rebased

2021-01-19 03:57 UTC, AllForNothing approved these changes
lgtm

2021-01-19 08:01 UTC, Vad1mo approved these changes
good work

2021-01-19 09:12 UTC, danfengliu approved these changes

2021-01-19 09:12 UTC, merged