Fix UI issues with label 2.2.0
goharbor/harbor pull request #14151
Opened 2021-02-03 08:41 UTC by AllForNothing

Fixes #13977
Fixes #14143
Signed-off-by: AllForNothing <sshijun@vmware.com>

2021-02-03 08:57 UTC, xuelichao approved these changes
LGTM

2021-02-03 09:43 UTC, Vad1mo requested changes
I made some suggestions regarding the german translation:

2021-02-03 09:43 UTC, Vad1mo commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "UNKNOWN_TIP": "Please verify whether the user has admin status through the Identity Provider System if the value is \"Unknown\""
Bitte überprüfen Sie, ob der Benutzer über den Identity Provider den Status "Admin" hat, wenn der Wert \"Unknown\" lautet.

2021-02-03 09:43 UTC, Vad1mo commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "UNKNOWN": "Unknown",
Unbekannt

2021-02-04 02:31 UTC, jwangyangls approved these changes
lgtm

2021-02-04 02:32 UTC, merged