Remove external_redis.port from migration script since not used since v1.10.0
goharbor/harbor pull request #14312
Opened 2021-02-25 17:11 UTC by sixeIa

Hello,

Trying to update Harbor from v2.1.2 to 2.2.0, we faced an issue due to how jinja2 template is made.
We are using redis+sentinel and we were unable to make the migration works.

Navigating to the jinja2 template you made, it allowed me to see a field "{{ external_redis.port }}" was used but removed since v1.10.0 (version since when you're supporting redis and redis+sentinel).

Anyway, removing this field allowed me to migrate my harbor.yml file.

I don't know if there are side-effects for such a modification but don't hesitate to tell me if there is something more to change.

Alexis

_(I made a PR few minutes ago but she wasn't following your contribution requirements)_

2021-03-04 12:56 UTC, sixeIa commented
Hello,

Any news about this PR ? I saw on Slack that other people where facing the same issue.

Thank you,

2021-04-06 09:10 UTC, bitsf commented
this `external_redis.port` is just used for migrate from 2.0.x to 2.1.x, so it is not correct after 2.1.
however if user upgrade from 2.0.x to 2.2.x directly, the fix would still have problem.

@ninjadq can you check how should this be fixed in migrate script

2021-04-06 09:15 UTC, sixeIa commented
Hi,

Oh yep okay, so there is an issue when bumping version as you told.
If you have any idea on how I can improve it, don't hesitate to tell me.

2021-04-06 09:38 UTC, ninjadq requested changes

2021-04-06 09:38 UTC, ninjadq commented on make/photon/prepare/migrations/version_2_0_0/harbor.yml.jinja
> +  host: {{ external_redis.host }}
it didn't need to remove `{{ external_redis.port }}`

2021-04-06 09:38 UTC, ninjadq commented on make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
> +  host: {{ external_redis.host }}
the same as above, `external_redis.port` must exist here.

2021-04-06 09:38 UTC, ninjadq commented on make/photon/prepare/migrations/version_2_2_0/harbor.yml.jinja
> +  host: {{ external_redis.host }}
only remove `:{{ external_redis.port }}` here is enough

2021-04-06 11:59 UTC, sixeIa reviewed
Modifications done

2021-04-07 06:50 UTC, ninjadq approved these changes
lgtm

2021-04-07 07:58 UTC, bitsf approved these changes

2021-04-07 07:58 UTC, merged

2021-04-08 12:40 UTC, wilsonge commented
@bitsf Thanks for merging this. Is there any chance this can be cherry-picked back into the 2.2 branch as otherwise we won't be able to take advantage of this fix until 2.3 obviously...