Enabled Prometheus for Jobservice
goharbor/harbor pull request #14463
Opened 2021-03-17 02:28 UTC by ninjadq

* Add prom server on jobservice
* Enabeld configs in templates
* Enabeld jobservice metrics in nginx

Signed-off-by: DQ <dengq@vmware.com>

2021-03-18 02:45 UTC, ninjadq commented
![image](https://user-images.githubusercontent.com/1069785/111565802-fe0dcb00-87d6-11eb-9988-a2acaec84d33.png)

2021-03-18 03:04 UTC, bitsf approved these changes

2021-03-19 07:00 UTC, steven-zou requested changes
please do changes

2021-03-22 06:39 UTC, heww commented on src/vendor/github.com/gocraft/work/worker_pool.go
> +
DO NOT EDIT files in vendor manually, please update them through go.mod and go.sum.

2021-03-22 06:41 UTC, heww requested changes
DO NOT EDIT files in vendor manually, please update them through go.mod and go.sum.

2021-03-22 06:45 UTC, steven-zou approved these changes
Please make sure the code coverage diff is in a reasonable scope.

2021-03-30 09:58 UTC, heww approved these changes

2021-03-30 10:08 UTC, merged