add Arksec logo in Harbor Adopters
goharbor/harbor pull request #16143
Opened 2021-12-20 10:24 UTC by simonsuns

add Arksec logo in Harbor Adopters

2022-01-04 08:45 UTC, bitsf approved these changes

2022-02-23 11:55 UTC, OrlinVasilev commented
@simonsuns - please fix the path and also please provide few sentences about your use case thanks!

2022-02-23 11:56 UTC, OrlinVasilev requested changes
fix path and provide use case ! thanks!

2022-02-23 11:56 UTC, OrlinVasilev commented on ADOPTERS.md
> +<a href="https://www.arksec.cn" target="_blank" border="0"><img alt="Arksec" src="https://raw.githubusercontent.com/simonsuns/website/master/docs/img/adopters/arksec.png" height="40"></a>&nbsp; &nbsp
@simonsuns please provide path from the main goharbor/website path!

2022-09-01 09:03 UTC, closed without merging