Update docker building for UI
goharbor/harbor pull request #16692
Opened 2022-04-12 12:31 UTC by AllForNothing

Strengthen  location regex to make sure API requests are forwarded to the backend
Signed-off-by: AllForNothing <sshijun@vmware.com>

2022-04-13 10:08 UTC, YangJiao0817 approved these changes

2022-04-13 12:17 UTC, wy65701436 approved these changes
lgtm

2022-04-13 12:18 UTC, wy65701436 requested changes
please add more comments to describe why

2022-04-18 03:05 UTC, wy65701436 approved these changes
lgtm

2022-04-18 03:07 UTC, merged