Allow the Identity Provider to be the primary auth method in Harbor.
goharbor/harbor pull request #17627
Opened 2022-10-04 11:41 UTC by tpoxa

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. **release-note/new-feature**
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2022-10-17 06:36 UTC, wy65701436 commented
@tpoxa can you please help to give more details on this PR?

2022-10-19 09:50 UTC, tpoxa commented
@wy65701436 well, oidc users always have to make an extra click time during sign-in; when this option is on, UI should redirect to the oidc provider directly. That was the plan.

2022-11-20 21:15 UTC, Vad1mo requested changes
For the language files, where you can't provide a translation, please copy&paste the English text.

- es-es-lang.json
- fr-fr-lang.json
- pt-br-lang.json
- tr-tr-lang.json
- zh-cn-lang.json
- zh-tw-lang.json

2022-11-20 21:15 UTC, Vad1mo commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "PRIMARY_AUTH_MODE": "Dieser Anmeldemodus wird zur Standardmethode für die Benutzeranmeldung. Der Anmeldebildschirm, in dem der Benutzer auswählt, ob er sich über den Identitätsanbieter oder
This is an error. Here shouldn't be the text for the tooltip. It should be the label name: **Primärer Anmeldemodus**

2022-11-20 21:15 UTC, Vad1mo commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "PRIMARY_AUTH_MODE": "Dieser Anmeldemodus wird zur Standardmethode für die Benutzeranmeldung. Der Anmeldebildschirm, in dem der Benutzer auswählt, ob er sich über den Identitätsanbieter oder
L905 after auth_mode should contain the tooltip.


`        "PRIMARY_AUTH_MODE": "Dieser Anmeldemodus wird zur Standardmethode für die Benutzeranmeldung. Der Anmeldebildschirm, in dem der Benutzer auswählt, ob er sich über den Identitätsanbieter oder über die lokale DB anmelden möchte, leitet den Benutzer automatisch an diesen Identitätsanbieter weiter. Die Anmeldung über die DB ist möglich, wenn die URL '/account/sign-in' explizit aufgerufen wird."`

2022-11-21 08:57 UTC, Vad1mo approved these changes
Looks good

2022-11-25 15:41 UTC, OrlinVasilev commented
That's great!!! @Vad1mo @tpoxa

2022-11-27 21:45 UTC, Vad1mo approved these changes

2022-11-28 09:41 UTC, stonezdj commented
LGTM

2022-11-28 15:35 UTC, OrlinVasilev commented
@stonezdj can you approve again

2023-02-06 09:16 UTC, stonezdj approved these changes

2023-02-07 04:52 UTC, AllForNothing commented
@tpoxa Please `cd src/portal`, then run `npm run lint_fix` to fix any lint-errors, then you can pass the UI-UT check.

2023-02-07 05:01 UTC, AllForNothing commented
@Vad1mo I had a try on my own env.  This looks fine to me

2023-02-07 05:01 UTC, AllForNothing approved these changes
LGTM

2023-02-08 13:17 UTC, Vad1mo approved these changes

2023-02-08 17:11 UTC, merged

2023-04-14 12:29 UTC, till commented
@yanji09 does this fix api calls for idp users as well?

2023-08-14 11:17 UTC, Rekhaprakash1 commented
@tpoxa @Vad1mo Is this feature available for API as well ?