Fix typos in common.sh
goharbor/harbor pull request #18151
Opened 2023-01-31 20:35 UTC by Maxi-Mega

Signed-off-by: Maxi_Mega <52792549+Maxi-Mega@users.noreply.github.com>

# Comprehensive Summary of your change

- Fix two typos in make/common.sh

Please indicate you've done the following:
- [X] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-02-01 14:21 UTC, OrlinVasilev commented on make/common.sh
> +}
```suggestion
}

```

2023-02-01 14:22 UTC, OrlinVasilev requested changes
Hi @Maxi-Mega  thanks for considering contribution to our project :) please add new line at the end!

Thank you!

2023-02-06 10:24 UTC, OrlinVasilev approved these changes
lgtm

2023-02-15 05:51 UTC, wy65701436 approved these changes
lgtm

2023-04-17 08:56 UTC, merged