Add webhook support for Microsoft Teams
goharbor/harbor pull request #18309
Opened 2023-03-06 17:53 UTC by akshatdalton

Fixes: #13395 and fixes: #12726.

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-03-15 03:09 UTC, chlins commented
Thanks for your contribution, but let's hold on this PR as it conflict with webhook refactor in the v2.8.

2023-03-15 03:10 UTC, chlins requested changes
hold on

2023-04-17 07:09 UTC, chlins commented
@akshatdalton Hi, the code base has been updated, could you rebase the main branch and rework your pr? Thanks!

2023-05-02 09:22 UTC, OrlinVasilev commented
@akshatdalton hey mate can you check ^^ thanks!

2023-05-13 20:58 UTC, akshatdalton commented
@chlins I've updated my PR please review!

2023-05-16 01:08 UTC, chlins commented
@akshatdalton Thanks for your work, However, it seems that what you have modified and what we expect after refactoring are not quite consistent in terms of easily implementing a new payload format. In theory, you only need to implement a payload format interface instead of a new job. You can refer to the implementation of CloudEvents: https://github.com/goharbor/harbor/blob/main/src/pkg/notifier/formats/cloudevents.go

2024-01-15 06:15 UTC, wy65701436 commented
@akshatdalton Do you still have an interest in working on this PR? If so, we could consider marking it as a candidate for the v2.11.

2024-03-15 22:34 UTC, szpak commented
> @akshatdalton Do you still have an interest in working on this PR? If so, we could consider marking it as a candidate for the v2.11.

@akshatdalton Will you time to finish this PR?

2024-07-29 20:06 UTC, szpak commented
I would prefer to keep it open.

2024-09-29 17:08 UTC, szpak commented
@akshatdalton Will you have time to finish this PR?

2024-09-29 19:36 UTC, Thesuperkingofsnakes22 approved these changes

2024-09-29 19:36 UTC, Thesuperkingofsnakes22 commented on src/controller/webhook/controller_test.go
>  	err = c.ctl.DeletePolicy(context.TODO(), 1)
**
```suggestion
 	err = c.ctl.DeletePolicy(context.TODO(), 1)@Vad1mo 
```
**

2024-12-30 09:04 UTC, closed without merging