feat(registry): support AssumeRoleWithWebIdentity for S3
goharbor/harbor pull request #18686
Opened 2023-05-16 10:48 UTC by DavidSpek

# Comprehensive Summary of your change

This PR adds patches to the building of the Harbor registry image that update the AWS SDK and fix how the AWS S3 client is created so that it can use `AssumeRoleWithWebIdentity` through IRSA.

The upstream PRs used in the patches are https://github.com/distribution/distribution/pull/3921 that change the way the client is created and https://github.com/distribution/distribution/pull/3599 that updates the AWS SDK. I have built the image that results from this PR and verified I can push new images to Harbor while using IRSA.

# Issue being fixed
Fixes #16490 and #12888

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-06-05 09:45 UTC, DavidSpek commented
Friendly ping @Vad1mo @wy65701436 @MinerYang

2023-06-14 09:55 UTC, DavidSpek commented
@Vad1mo Sorry for the late response. When is the next community meeting?

2023-06-26 10:13 UTC, daemon-ian commented
Hi @Vad1mo @wy65701436 @MinerYang - are we clear what the next steps are for getting this merged? It feels like we're really close to getting this long standing issue sorted. Thanks @DavidSpek for putting this in.

2023-06-27 10:37 UTC, DavidSpek commented
@OrlinVasilev maybe you can also weigh in here.

2023-06-28 06:23 UTC, OrlinVasilev commented
@DavidSpek Thank you :)) see you later :)

2023-06-28 09:07 UTC, wy65701436 requested changes
holding to discuss

2023-06-28 09:25 UTC, wy65701436 commented
I'm against this change because we do not want to maintain any forked or modified codebase that deviates from the original one. Instead, we should align with the upstream release cadence and pick up the next release that contains the two PRs. While we currently only have two or three backports that do not have any conflicts, we need to consider the long-term maintenance of our codebase.

Furthermore, the redis patch is critical for users who want to enable redis high availability in sentinel. We only have one patch, which is not likely to conflict with other changes.

2023-06-28 11:03 UTC, peterellisjones commented
Without this change Harbor is not be suitable for most enterprise users using EKS.

1. Multiple registry replicas are required for harbor to be HA
2. With multiple replicas, the registry deployment only works with an external blobstore, not filesystem storage. On AWS, this means S3.
3. Without this PR, Harbor can only authenticate with S3 via static credentials (access key), not IRSA
4. No enterprise security team wants static S3 credentials floating around when IRSA exists.

2023-06-28 11:54 UTC, OrlinVasilev commented
Hi @peterellisjones can you join us later today so we can all discuss that, @wy65701436 can you please also join :)

2023-06-28 12:20 UTC, mhrabovcin commented
I would be in favour of merging this PR as there is no clear timeline in the upstream `registry` project when there will be a supported release (v3 or patched v2.x) that can use dynamic AWS credentials.

2023-09-06 09:11 UTC, dkulchinsky commented
not stale

2023-11-06 10:23 UTC, ichasco-heytrade commented
not stale

2023-11-22 13:09 UTC, OrlinVasilev commented
@wy65701436 and @DavidSpek any progress on that?

2023-11-22 15:30 UTC, peterellisjones commented
Would love to see some progress on this. IMHO without support for IAM creds Harbor is not really an appropriate product for enterprise users

2023-11-22 16:05 UTC, OrlinVasilev commented
@peterellisjones absolutely, that's the reason I'm trying to prioritize that :) @msha01 can you put that in the log please!

2024-01-22 09:52 UTC, Vad1mo commented
We should close or update this PR.

Harbor depends on upstream docker distribution, and we are not hard forking docker distribution. We only apply PRs that are in the main branch, but where a release is not published yet. 

It looks like that all of the upstream PRs have been closed 

- https://github.com/distribution/distribution/pull/3599
- https://github.com/distribution/distribution/pull/3921

The consequence here is **A** to update this PR or **B** close this PR.

2024-05-23 11:13 UTC, Alwin-Stockinger commented
not stale

2024-07-05 04:11 UTC, kingbj940429 commented
Is it currently in progress?

I also have to use AWS IRSA..

If not supported, I'm sad..

2024-07-08 08:22 UTC, OrlinVasilev commented
@davidspek can you check @Vad1mo remarks and update?

2024-07-11 17:34 UTC, davidspek commented
This PR probably shouldn’t be merged as it was a crazy hack. Instead distribution should be updated to v3 since that release will happen soon. v3-beta.1 was released yesterday. https://github.com/distribution/distribution/releases/tag/v3.0.0-beta.1. @OrlinVasilev @Vad1mo maybe Harbor should start testing with distribution v3 already.

2024-07-11 17:34 UTC, closed without merging