【UT】add unit test for collector system info
goharbor/harbor pull request #18717
Opened 2023-05-23 07:29 UTC by lengrongfu

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

add unit test for collector system info.

# Issue being fixed
Fixes #(issue)

/label release-note/enhancement

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-06-01 05:57 UTC, wy65701436 commented
thanks @lengrongfu for your contribution, please add description of the PR according to [this](https://github.com/goharbor/harbor/pull/18727#issuecomment-1569557151).

2023-06-02 05:40 UTC, chlins requested changes
The change looks good to me, but please complete the description for this PR, then we can move forward it to merge, thanks.

2023-06-08 01:01 UTC, chlins approved these changes
lgtm

2023-06-08 02:04 UTC, stonezdj approved these changes

2023-06-08 02:06 UTC, merged