8614 regex replication filters
goharbor/harbor pull request #18723
Opened 2023-05-23 17:29 UTC by WilfredAlmeida

This PR aims to add regular expression based replication rules feature to Harbor.

Issue: [8614](https://github.com/goharbor/harbor/issues/8614)
Community Proposal: [221](https://github.com/goharbor/community/pull/221)

The filter functions for regex-based filtering are defined in the `src/pkg/reg/filter/artifact.go` file alongside the existing filtering functions using the double star logic.

Necessary schema properties are added in the `policy.go` file.

The decision on the finalized approach to add the feature is discussed in the community proposal [221](https://github.com/goharbor/community/pull/221)

2023-05-24 01:58 UTC, WilfredAlmeida commented
I am aware that there are print statements in the code. They are there for personal debugging reference and will be removed in the mergeable PR.

2023-07-03 04:22 UTC, WilfredAlmeida commented
The latest commit [edf8c20](https://github.com/goharbor/harbor/pull/18723/commits/edf8c20b557a33b0341f3a9ef819381ed64deee1) removes some unnecessary and error causing Angular properties from the portal.

The properties are for radio input for choosing filter mode between regex & double star

2023-07-03 08:41 UTC, OrlinVasilev commented
@Vad1mo and @wy65701436 can you review this one please :)

2023-07-03 08:41 UTC, OrlinVasilev commented
@WilfredAlmeida please fix DCO

2023-07-03 09:41 UTC, WilfredAlmeida commented
I'll fix the DCO issue and update here.

2023-07-08 17:32 UTC, WilfredAlmeida commented
@OrlinVasilev I've rebased and fixed the DCO for my commits.

2023-07-14 09:52 UTC, Vad1mo requested changes
some tests seem to fail, and you are missing the DCO

2023-07-14 09:58 UTC, WilfredAlmeida commented
@Vad1mo @OrlinVasilev In between my commits, I synced my fork with the main repo. Now when I'm trying to fix DCO it's adding it to commits that are not mine.

My first commit was on May 10th and when I do a rebase its rewriting the commits of others as well.

Is there a way I can only add DCO to my commits?

2023-08-18 10:26 UTC, WilfredAlmeida commented
@Vad1mo @OrlinVasilev I've fixed the DCO and other occurring issues. Please let me know if any more actions are required from my side.

2023-10-23 12:21 UTC, kristianhaukeland commented
Still relevant

2024-02-28 21:06 UTC, Vad1mo approved these changes

2024-10-29 06:35 UTC, wy65701436 commented
@WilfredAlmeida thanks for your contribution.


To support regex in Harbor, I propose creating a shared library of regex patterns, similar to the double star we currently use. This library would apply across all Harbor functionalities, including replication and tag retention, making it easier to enable consistent functionality for tag retention.

If you’re still willing to work on this pull request, @chlins and I will do our best to assist you from a technical perspective.

2024-10-29 07:44 UTC, WilfredAlmeida commented
Hello @wy65701436, currently I don't have the bandwidth to work this and won't be able to do so anytime soon

2024-11-08 06:48 UTC, wy65701436 commented
Thanks, @WilfredAlmeida, for your response. Given this, I believe we can temporarily close this pull request until we have someone from the community who can assist.

2025-08-25 08:46 UTC, reasonerjt commented
Closing this one per comment:
https://github.com/goharbor/harbor/pull/18723#issuecomment-2463900889

b/c the author has stopped working on it.

We can use this PR as a reference when we wanna introduce regex support to replication filters.

2025-08-25 08:46 UTC, closed without merging