Add a tooltip for slack notification
goharbor/harbor pull request #18787
Opened 2023-06-05 03:54 UTC by AllForNothing

1.Fixes #18507
2.Remind the users of Slack's rate limits
<img width="896" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/c9af4745-d552-43aa-8079-cb0b33a4d89d">

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-06-05 03:57 UTC, AllForNothing commented
@OrlinVasilev Can you help to review the English text for the added tooltip?
We want to remind the users of the rate limits for Slack(https://api.slack.com/docs/rate-limits)

2023-06-05 05:24 UTC, OrlinVasilev requested changes

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/en-us-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/de-de-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/es-es-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/fr-fr-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/pt-br-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/tr-tr-lang.json
> +        "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/zh-cn-lang.json
> +        "SLACK_RATE_LIMIT": "请注意 Slack 的速率限制"
```suggestion
        "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "SLACK_RATE_LIMIT": "Please be ware of the rate limits for Slack"
```suggestion
    "SLACK_RATE_LIMIT": "Please be aware of Slack Rate Limits"
```

2023-06-05 05:24 UTC, OrlinVasilev commented
@AllForNothing suggested changes

2023-06-05 06:36 UTC, AllForNothing commented
@OrlinVasilev Thanks for the comments. PR updated

2023-06-05 09:17 UTC, OrlinVasilev approved these changes
lgtm

2023-06-06 10:04 UTC, chlins approved these changes
lgtm

2023-06-07 08:14 UTC, merged