artifact - No need to check len when ranging over slice
goharbor/harbor pull request #18930
Opened 2023-07-13 10:08 UTC by dioguerra

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

Drop extra condition to check for unrequired len of slice.

# Issue being fixed
Fixes #(issue)
No issue, just an optimization (maybe).
I'm not sure how exactly the golang compiler works so feel free to educate me :).
I now that slice keeps an internal track of the slice lenght so i'm pretty sure that check for len for empty objects should be faster than calling range. But i went ahead and risk it just to get a second opinion.
With the increase of SBOMs and Signatures, it should be faster just to drop the check and go for the cycle. It is easy on the eyes also.

Can you commend?

/release-note/ignore-for-release

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-07-14 03:04 UTC, wy65701436 commented
thanks for the contributing, did you regression on the artifact copy scenario, especially three layers artifact. 

```
artifact 
 - sbom
       signature(signature of the sbom)
 - signature
```

2023-07-14 12:05 UTC, dioguerra commented
I tried, 

Artifact (ingress-list)
Signature
Refs:
  - manifest-arch1
    Signature
  - manifest-arch2
    Signature
  - manifest-arch3
    Signature

2023-07-17 05:42 UTC, zyyw approved these changes

2023-07-17 09:06 UTC, wy65701436 commented
I would like to keep it, since the condition can be easily interpreted as readable - if something doesn't exist, then we won't do something.

2023-07-17 09:06 UTC, wy65701436 requested changes
hold for discussing

2023-08-17 09:03 UTC, closed without merging