Update zh-tw (Traditional Chinese) locale
goharbor/harbor pull request #19161
Opened 2023-08-13 18:06 UTC by PeterDaveHello

Improve zh-tw (Traditional Chinese) locale again. This is a follow up of #18608, and this time I try to refer to the en-us locale, also compare more references for the terms, although there are still some terms or strings not very perfect yet(I mean it's hard to be translated), hopefully the zh-tw language is at least more consistent and localized here now.

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-08-14 04:03 UTC, AllForNothing commented
@PeterDaveHello Very lovely to see a follow-up PR.
Also, can you invite someone who is a native speaker to help to review the changes? thanks!

2023-08-14 05:42 UTC, wy65701436 approved these changes
lgtm, thanks.

2023-08-14 06:24 UTC, Vad1mo approved these changes

2023-08-14 06:25 UTC, Vad1mo approved these changes

2023-08-14 08:25 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "ARTIFACTS": "Artifact(s)",
```suggestion
    "ARTIFACTS": "產出物",
```

2023-08-14 08:26 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "TOP_5_ARTIFACT": "前五名危險的 Artifacts",
```suggestion
    "TOP_5_ARTIFACT": "前五名危險的產出物",
```

2023-08-14 08:28 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
>      "ARTIFACTS_COUNT": "Artifact 數量",
```suggestion
    "ARTIFACTS_COUNT": "產出物數量",
```

2023-08-14 08:28 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
>      "ARTIFACTS": "Artifacts",
```suggestion
    "ARTIFACTS": "產出物",
```

2023-08-14 08:28 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "FILTER_FOR_ARTIFACTS": "篩選",
```suggestion
    "FILTER_FOR_ARTIFACTS": "篩選產出物",
```

2023-08-14 08:28 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "PLACEHOLDER": "未發現任何 artifacts！",
```suggestion
    "PLACEHOLDER": "未發現任何產出物！",
```

2023-08-14 09:11 UTC, AllForNothing requested changes
Please resolve all the comments

2023-08-14 16:43 UTC, PeterDaveHello commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "CHART_COUNT": "Chart 數量",
Thanks @pichuang

2023-08-14 16:43 UTC, PeterDaveHello commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "DESTINATION_NAMESPACE": "指定目的端命名空間。如果不填，資源會被放到和源相同的命名空間下。",
Nice catch, thanks!

2023-08-14 16:48 UTC, PeterDaveHello commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "DESTINATION_NAMESPACE": "指定目的端命名空間。如果不填，資源會被放到和源相同的命名空間下。",
Interesting, looks like I dropped the change/fix for it before commit it ... fixed now anyway and thanks again.

2023-08-14 17:57 UTC, pichuang commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "ARTIFACTS": "Artifact(s)",
I just looked at examples from other companies, and it looks like no one is translating this word. I think we can keep Artifacts going until there are tons of examples.

2023-08-15 10:45 UTC, PeterDaveHello commented on src/portal/src/i18n/lang/zh-tw-lang.json
> +    "ARTIFACTS": "Artifact(s)",
Fine with me.

2023-08-15 10:45 UTC, PeterDaveHello commented
@AllForNothing looks like we are good to go!

2023-08-16 01:57 UTC, AllForNothing approved these changes

2023-08-16 01:57 UTC, merged