Add a tooltip for the page title of security hub
goharbor/harbor pull request #19231
Opened 2023-08-22 08:08 UTC by AllForNothing

<img width="1015" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/e668fecc-fa4e-4338-9d88-4db69a5d50ec">

1. This tooltip explains the artifacts total count

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-08-22 08:35 UTC, AllForNothing commented
@Vad1mo We are trying to add a tooltip for the artifact total count:
<img width="370" alt="image" src="https://github.com/goharbor/harbor/assets/30999793/02f4ada1-0e63-42af-ac57-70a326826fc2">
total count = artifacts + accessories + child artifact of index + child artifact of CNAB
Any suggestions for the English text?

2023-08-22 08:51 UTC, stonezdj approved these changes

2023-08-23 09:05 UTC, Vad1mo requested changes

2023-08-23 09:05 UTC, Vad1mo commented on src/portal/src/i18n/lang/fr-fr-lang.json
> +        "PAGE_TITLE_TOOLTIP": "The total artifact count includes artifact accessories, child artifacts of the image index, and child artifacts of CNAB artifacts"
The total artifact count also includes artifact accessories, OCI Image Index child artifacts, and CNAB child artifacts

2023-08-23 09:05 UTC, Vad1mo commented on src/portal/src/i18n/lang/en-us-lang.json
> +        "PAGE_TITLE_TOOLTIP": "The total artifact count includes artifact accessories, child artifacts of the image index, and child artifacts of CNAB artifacts"
The total artifact count also includes OCI artifact accessories, OCI Image Index child artifacts, and CNAB child artifacts

2023-08-24 09:37 UTC, wy65701436 approved these changes
lgtm

2023-08-24 10:21 UTC, merged