feat: add extra host for docker compose
goharbor/harbor pull request #19409
Opened 2023-10-01 05:40 UTC by Notekunn

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2023-10-01 07:12 UTC, Vad1mo approved these changes

2023-10-10 08:44 UTC, stonezdj requested changes
It is better to update the docker-compose.yaml file directly.

2023-10-20 05:03 UTC, wy65701436 commented
It sounds like an customization, rather than a feature. User could do this at their end by editing the yaml file directly as @stonezdj mentioned.

2023-10-21 08:03 UTC, closed without merging

2024-06-27 07:51 UTC, hurdonkey commented
I think this feature is very useful, since I've been using harbor, most of the weird problems come from the hosts inside the container, if we have to manually maintain them in the docker-compose.yaml, it's very unfavorable for the later update, I'm counting on the hosts to be automatically maintained in harbor.yml!