Add SBOM scan REST API
goharbor/harbor pull request #20215
Opened 2024-04-02 09:50 UTC by stonezdj

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-04-02 20:58 UTC, Vad1mo requested changes

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +          description: Specify whether the generate sbom overview is include inside the returning artifacts
Specify whether the SBOM overview is included with the returning artifacts.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +          description: Specify whether the sbom overview is inclued inside the returning artifacts
Specify whether the SBOM overview is included with the returning artifacts.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +          description: Specify whether the generate sbom overview is include inside the returning artifacts
It is not clear from the description what this "**overview**" it? Can you elaborate on that? As a consumer of the API, I would assume there is also a more detailed response available.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: The overview of the generate SBOM
The overview of the generated SBOM.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: 'The scan type for scan requst, it could be vulnerability or sbom'
The scan type for the scan request. Two options are currently supported, `vulnerability? and `sbom`.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: 'The start time of the scan process that generating report'
The start time of the scan process that is generating the report.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: 'The end time of the scan process that generating report'
The end time of the scan process that is generating the report.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: 'The status of the generate SBOM process'
The process status for the generated SBOM. 
> Here it is not clear what does the status report? Fail Success or more? What can the user find in the satus?

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: 'The seconds spent for generating the report'
Time in seconds required to create the report.

2024-04-02 20:58 UTC, Vad1mo commented on api/v2.0/swagger.yaml
> +        description: Indicate the scanner's properties such as support_vulnerability or support_sbom
Indicates the capabilities of the scanner, e.g. support_vulnerability or support_sbom.

2024-04-03 02:04 UTC, wy65701436 approved these changes
lgtm

2024-04-03 07:32 UTC, zyyw commented on api/v2.0/swagger.yaml
> +        type: string
should this be an enum?

2024-04-03 07:34 UTC, zyyw approved these changes

2024-04-03 08:38 UTC, merged