README.md: add artifact hub badge
goharbor/harbor pull request #20736
Opened 2024-07-12 21:23 UTC by mohamedawnallah

# Comprehensive Summary of your change

In this commit, we add the artifact hub badge for the harbor project to improve their discoverability and the best practices
index on [clonmonitor.io](https://clomonitor.io/projects/cncf/harbor).

# Screenshots
<img width="983" alt="Screenshot 2024-07-13 at 12 21 03 AM" src="https://github.com/user-attachments/assets/306321be-0b4e-476f-901b-41d7d941b2de">

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-07-13 14:19 UTC, Vad1mo approved these changes

2024-07-15 08:30 UTC, wy65701436 requested changes
we should put this into the helm repoistiory, cc @MinerYang

2024-07-22 09:54 UTC, Vad1mo commented
> we should put this into the helm repoistiory, cc @MinerYang

I think it also makes sense to have it here.

2025-01-12 21:39 UTC, mohamedawnallah commented
Hi @Vad1mo, @wy65701436, and @MinerYang,

How I am supposed to move this PR forward? 🙏

2025-01-12 21:40 UTC, mohamedawnallah commented
Hi @Vad1mo, @wy65701436, and @MinerYang,

How am I supposed to move this PR forward? 🙏

2025-03-05 03:31 UTC, bupd approved these changes
lgtm

2025-06-05 11:04 UTC, Vad1mo commented
@goharbor/maintainers can you guys have a look, its a tiny thing improving the visibility for the user.

2025-06-05 11:11 UTC, OrlinVasilev approved these changes

2025-06-05 11:13 UTC, merged