Extend oidc_cli security context generator to include calls to the v2…
goharbor/harbor pull request #20851
Opened 2024-08-14 11:04 UTC by LGhoull

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

- Extend oidc_cli security context generator to include calls to the v2 API
- remove idtoken security context generator
- rename and consolidate tests and names accordingly

Id Tokens can no longer be used to authenticate against the v2 API
Instead, basic auth with the CLI secret as password must be used.

The use of the OIDC ID token as a bearer token for authentication against the API is inconvenient since the ID token is hard to get as a normal user.

# Issue being fixed
Fixes #14236

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-08-14 12:41 UTC, LGhoull commented
Definitely a breaking change, but I can't add labels.

2024-08-15 07:51 UTC, reasonerjt commented
Although the change is relatively small, b/c this is a break change and involves security. I wish to suggest that a proposal is needed for review and get approval from maintainers.

If we reach a consensus to do this, there should also be some change needed in UI and Documentation.

2024-08-15 07:52 UTC, reasonerjt requested changes
Please write a proposal and get approval first.

2024-08-19 09:49 UTC, LGhoull commented
Proposal: https://github.com/goharbor/community/pull/250

2024-10-24 12:36 UTC, LGhoull commented
Still relevant

2025-06-05 09:04 UTC, closed without merging