Skip admin and change oidc user not found message more readable
goharbor/harbor pull request #21061
Opened 2024-10-18 08:30 UTC by stonezdj

fixes #21041

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-10-25 07:02 UTC, OrlinVasilev commented
+1

2024-12-18 13:28 UTC, peters-david commented
+1

2024-12-18 20:44 UTC, Vad1mo requested changes

2024-12-18 20:44 UTC, Vad1mo commented on src/server/middleware/security/oidc_cli.go
> +			return nil
Log at debug level for admin users as this might be expected

logger.Debugf("OIDC verification failed for admin user %s: %v", username, err)

2024-12-18 20:44 UTC, Vad1mo commented on src/pkg/oidc/secret.go
> +	if strings.Contains(err.Error(), "no row found") {
Checking error strings is fragile. Would not be better to:
1.  Use proper error types or sentinel errors
2. Check if the error implements a specific interface

2025-01-02 07:52 UTC, stonezdj commented on src/pkg/oidc/secret.go
> +	if strings.Contains(err.Error(), "no row found") {
Updated

2025-01-02 07:52 UTC, stonezdj commented on src/server/middleware/security/oidc_cli.go
> +			return nil
No need to dump information for admin user.

2025-01-02 08:53 UTC, wy65701436 commented on src/server/middleware/security/oidc_cli.go
> +		user, err2 := uctl.GetByName(ctx, username)
We should avoid calling the uctl.GetByName twice, I suggest rewriting it as following:

```
        u, err := uctl.GetByName(ctx, username)
	if err != nil {
		logger.Errorf("failed to get user model, username: %s, error: %v", username, err)
		return nil
	}

	info, err := oidc.VerifySecret(ctx, username, secret)
	if err != nil {
		if u.UserID == 1 {
			return nil
		}
		logger.Errorf("failed to verify secret, username: %s, error: %v", username, err)
		return nil
	}
```

2025-01-02 08:56 UTC, wy65701436 commented on src/pkg/oidc/secret.go
> +	if errors.Is(err, orm.ErrNoRows) {
Can we move the check into the DAO? This would allow other callers to avoid duplicating the same logic.

2025-01-02 09:33 UTC, wy65701436 approved these changes
lgtm

2025-01-02 09:40 UTC, chlins approved these changes
lgtm

2025-01-03 02:58 UTC, merged