Add Russian language support
goharbor/harbor pull request #21083
Opened 2024-10-24 01:29 UTC by sergey-akhmineev

Thank you for contributing to Harbor!

# Comprehensive Summary of your change
Added support for the Russian language, including translations for UI elements and configuration files.

# Issue being fixed

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/new-feature"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-10-24 11:44 UTC, OrlinVasilev commented
Hi @sergey-akhmineev great stuff but we would need another russion speaker to verify the translation if you don't mind
and also we would love to have a long term support on the translation :)

2024-10-25 01:02 UTC, sergey-akhmineev commented
Hi @OrlinVasilev of course I don't mind, I understand everything. If you really want to, of course I will continue long term translation support.

2025-01-27 11:03 UTC, sias32 commented
When to expect?

2025-01-28 11:57 UTC, OrlinVasilev commented
Hi @sergey-akhmineev did you manage to find someone else to review it ? if not I will address that to the community again!

2025-01-28 12:00 UTC, OrlinVasilev commented
@Kalmanq, @vladrunk, @Nikemaks, @kosmos2uh, @mykyta-yaremenko, @msaichuk, @LexGlu, @yevhenkizin, @mykhailo-
samus, and @zOrc why did you voted 👎 on my request: https://github.com/goharbor/harbor/pull/21083#issuecomment-2435048999

2025-01-29 07:20 UTC, sias32 reviewed
I watched half of it and made a couple of comments

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "REPLICATE_FAILURE": "Запуск не удалось",
Думаю лучше будет "Запуск не удался"

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "STOP_FAILURE": "Остановка выполнения не удалась",
Думаю лучше будет "Остановить выполнение не удалось"

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "TIME_OUT": "Тайм-аут шлюза"
Думаю лучше будет "Шлюз не отвечает"

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "EMAIL": "Email",
Думаю лучше будет везде писать "Почта"

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "CONFIRM_TITLE_CLI_GENERATE": "Вы уверены, что можете повторно сгенерировать секрет?",
Думаю лучше будет "Вы уверены, что хотите перегенерировать секрет?"

2025-01-29 07:20 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "CONFIRM_BODY_CLI_GENERATE": "Если вы повторно сгенерируете секрет CLI, старый секрет CLI будет отброшен"
Думаю лучше будет "Если вы перегенерируете секрет CLI, старый секрет CLI будет отброшен"

2025-01-29 09:33 UTC, OrlinVasilev commented
Thank you @sias32 great stuff :) @sergey-akhmineev ^^

2025-01-30 03:56 UTC, sergey-akhmineev commented
@sias32 , @OrlinVasilev I've made the suggested changes to the translation, and I'm currently re-checking the translation. Thank you.

2025-02-14 18:41 UTC, franchb approved these changes
I am a native Russian language speaker and checked the translation for accuracy.

2025-02-24 01:48 UTC, sergey-akhmineev commented
@sias32 Hi, I've made the changes you suggested. Please check and confirm if everything is fine.

2025-02-24 07:06 UTC, sias32 requested changes
In my last sentence, "mail" is not translated everywhere

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "EMAIL": "Email должен быть действительным адресом, например name@example.com.",
Email -> Почта должна быть дейсвительным адресом

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "SIGN_UP_MAIL": "Email используется только для сброса пароля.",
Email -> Почта

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "COLUMN_EMAIL": "Email",
Email -> Почта

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "EMAIL": "Email",
Email -> Почта

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "CAPTION": "Введите ваш email, чтобы сбросить пароль",
Email -> Введите вашу почту

2025-02-24 07:06 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "EMAIL": "Email",
Email -> Почта

2025-02-24 07:09 UTC, sias32 commented
Overall, it's okay

2025-02-25 07:09 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "EMAIL": "Почта должена быть действительным адресом, например name@example.com.",
correct to "должна"

2025-02-25 07:09 UTC, sergey-akhmineev commented
@sias32, Hi, it's done

2025-02-25 07:13 UTC, sias32 requested changes
I completely forgot about "Harbor"

2025-02-25 07:13 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "PUSH_BASED": "Отправлять ресурсы с локального Харбора на удаленный реестр.",
Харбора -> Harbor

2025-02-25 07:13 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "PULL_BASED": "Получать ресурсы с удаленного реестра на локальный Харбор.",
Харбор -> Harbor

2025-02-25 07:13 UTC, sias32 commented on src/portal/src/i18n/lang/ru-ru-lang.json
> +        "CLI_PASSWORD_TIP": "Вы можете использовать этот секрет CLI как пароль при использовании docker/helm cli для доступа к Харбору.",
Харбору -> Harbor

2025-02-25 07:23 UTC, sias32 approved these changes
Nice

2025-02-26 08:36 UTC, sergey-akhmineev commented
@OrlinVasilev Hello, are two people enough? Or is more needed?

2025-03-26 14:21 UTC, OrlinVasilev commented
@sergey-akhmineev @franchb @sias32 I think we are done with this can you please confirm so we can merge this :)))
поздравления :)) (Bulgarian here)

2025-03-26 14:22 UTC, OrlinVasilev approved these changes
поздравления

2025-03-26 14:24 UTC, sias32 approved these changes

2025-05-06 02:30 UTC, sergey-akhmineev commented
@OrlinVasilev Hi, can you tell me, but besides @Vad1m, no one else can approve these changes? Apparently he doesn't have time, or he just doesn't want to.

2025-05-23 07:22 UTC, OrlinVasilev commented
I think that's is ready to be merged!

2025-05-23 07:22 UTC, OrlinVasilev commented
@Vad1mo can you please also check so we can have that in :)

2025-06-06 12:04 UTC, OrlinVasilev commented
@goharbor/all-maintainers it's time to merge this :)

2025-07-01 10:35 UTC, Vad1mo reviewed
I am hesitant to accept yet another language for the following reasons:

1. All translations are outdated. The only language probably close to English is Chinese, as many maintainers are from China(but not all PRs)
2. In the context of software/cloud native/IT etc. the common language is English, from the few languages I speak the IT terms are in English.
3. Many of the users who need and user Harbor are in this space, and understand the core English terms.  
4. On average, we receive 1–2 PRs per year, that contain updates to translations (we have 9 languages)
5. It looks ugly and unprofessional if a software is half translated! The only way to avoid that is not using translations altogether. 

My proposal to support translations in Harbor would be to supply them externally. Harbor should have a mechanism to allow reading a language files from a file system/URL/s3/git etc.. We should remove all languages from Harbor except English...

2025-07-01 11:22 UTC, OrlinVasilev commented
@Vad1mo that sounds like entirely new way of doing it, so new proposal and etc.... but totally makes sense to load external to the instance translation. We can have a translation repository and way of making it consistent and with all required checks like if all strings are translated etc....

2025-07-02 00:37 UTC, sergey-akhmineev commented
> I am hesitant to accept yet another language for the following reasons:
> 
> 1. All translations are outdated. The only language probably close to English is Chinese, as many maintainers are from China(but not all PRs)
> 2. In the context of software/cloud native/IT etc. the common language is English, from the few languages I speak the IT terms are in English.
> 3. Many of the users who need and user Harbor are in this space, and understand the core English terms.
> 4. On average, we receive 1–2 PRs per year, that contain updates to translations (we have 9 languages)
> 5. It looks ugly and unprofessional if a software is half translated! The only way to avoid that is not using translations altogether.
> 
> My proposal to support translations in Harbor would be to supply them externally. Harbor should have a mechanism to allow reading a language files from a file system/URL/s3/git etc.. We should remove all languages from Harbor except English...

The idea of implementing a mechanism to pull translations from external sources is excellent. However, I think it would take a lot of time, and I highly doubt that it should be a priority right now. As for translations, I’ve set up my own monitoring system to check for untranslated keys in the repository, so I’m keeping track of any new keys that appear and I’m committed to keeping the translations up to date. That’s why I’d like to ask you to include my translation, as I’ve put a lot of effort into it.

2025-07-02 08:51 UTC, OrlinVasilev commented
@sergey-akhmineev thank you for your contributions, fantastic work!!!
BTW can you show us the automation you did maybe we can adopt it for all translations and do a tests based on it:)

@Vad1mo please reconsider accepting the PR thanks!

2025-07-02 08:57 UTC, merged

2025-07-03 11:57 UTC, OrlinVasilev commented
@sergey-akhmineev Congratulations!!!

2025-07-03 12:21 UTC, sergey-akhmineev commented
> @sergey-akhmineev Congratulations!!!

Thanks, it wouldn't have worked without your help. Thank you so much! I'll drop the code I wrote to check the relevance of the translations later.

2025-09-18 08:22 UTC, atlet99 commented
Wow, what an amazing addition!  Thank you @sergey-akhmineev  and everyone involved for bringing Russian language support to Harbor. This truly makes the project more inclusive and approachable for a whole community of users - it doesn’t just translate UI labels, it builds a bridge, makes the project feel closer to our hearts. I’m genuinely impressed by the effort and craftsmanship here.

Keep it up, beast!