fix: replication rule message in UI
goharbor/harbor pull request #21299
Opened 2024-12-09 10:58 UTC by bupd

Thank you for contributing to Harbor!

# Comprehensive Summary of your change
- updates Replication Rule Execution confirm message in UI

# Issue being fixed
Fixes #21292

Please indicate you've done the following:
- [x] Well Written Title and Summary of the PR
- [x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-12-10 01:48 UTC, chlins commented on src/portal/src/i18n/lang/zh-cn-lang.json
> +        "REPLICATION_TITLE": "Confirm Replication Rule Execution",
It should be `zh-cn`.

2024-12-10 01:50 UTC, chlins requested changes
Some original language description has been translated into English, but it does not make sense.

2024-12-13 14:46 UTC, bupd commented
thanks for pointing out @chlins . The chinese version is already clear so will update only the other languages which is not clear.

2024-12-20 15:11 UTC, Vad1mo approved these changes

2024-12-24 09:10 UTC, chlins approved these changes
lgtm

2025-01-06 14:07 UTC, merged