Normalize the job queue latency's value
goharbor/harbor pull request #21355
Opened 2024-12-24 06:23 UTC by stonezdj

fix #21354

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-12-25 01:59 UTC, chlins approved these changes
lgtm

2024-12-25 16:56 UTC, bupd approved these changes
LGTM!

2024-12-26 09:30 UTC, wy65701436 requested changes

2024-12-26 09:30 UTC, wy65701436 commented on src/controller/jobmonitor/monitor.go
> +		if queue.Latency > 0 {
We should pause this PR for further discussion.

Personally, I don't think changing the negative number to 0 is the right approach. The latency should always be positive, and a negative value typically indicates a misconfiguration, such as when the system time on the worker node running harbor-core and harbor-jobservice are not synchronized with the same time server.

Adjusting the value to 0 might mask the underlying issue for the administrator. I prefer that we add a debug log to help identify the potential cause of this situation.

2025-03-27 09:04 UTC, closed without merging